### ISSUE TITLE
没有`goto-column'函数

### ISSUE THREAD

**Issue by pengpengxp** [manateelazycat/color-rg#1]
你好，我使用过程中发现，我的emacs里面没有 `goto-column' 这个函数。

我的emacs版本如下：

GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2018-06-15

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/color-rg/commit/2b86ce415d511c3ab51de0f5d010f30e7940c386 fixed

Thanks for report!
