### ISSUE TITLE
Wrong type argument: hash-table-p, ni

### ISSUE THREAD

**Issue by ipyffor** [manateelazycat/color-rg#100]
cd ~
emacs -q -l ~/.emacs.d/elpaca/repos/color-rg/color-rg.el
color-rg-search-input 输入test(搜索出来的结果很多)
![image](https://github.com/manateelazycat/color-rg/assets/47955238/0dc53cae-5121-47e6-93a1-6e7530d45b78)
 是不是搜索到一些二进制文件了

**Comment by manateelazycat** [comment]
color-rg 没有 hash-table-p 相关代码， 感觉不是 color-rg 的bug， 有重现步骤或者搜索文件样品吗?

**Comment by ipyffor** [comment]
好像在home目录下搜索，搜的东西很多就会这样，暂时没找到是搜索什么文件会触发

**Comment by ipyffor** [comment]
[test.zip](https://github.com/manateelazycat/color-rg/files/14811020/test.zip)
解压之后在test目录下搜索t会出现这个错误

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/color-rg/commit/4be33d9c7604576a98ecc671bd80fe6be342fdde

已经修复了， 感谢反馈
