### ISSUE TITLE
search-input-in-project error when cursor on JavaScript string

### ISSUE THREAD

**Issue by damanis** [manateelazycat/color-rg#102]
Emacs version: 31.0.50
Color-rg version: latest

Reproduce howto:
- Create empty file `qweqwe.js` and open it in Emacs
- Enter the text `'qwe'` and place cursor on `w`
- Call `color-rg-search-input-in-project`

**Expected**: `COLOR-RG Search:` prompt
**Observerd**: The error message `No available parser for this buffer: #<buffer qweqwe.js>`

- Move cursor to end of line (after `'`)
- Call `color-rg-search-input-in-project`

Works properly

**Comment by manateelazycat** [comment]
you need install treesit parser

**Comment by damanis** [comment]
I got `let: Wrong type argument: integer-or-marker-p, nil` with builtin `treesit` module (emacs 29.4).
Same scenario.

**Comment by manateelazycat** [comment]
You need config treesit like this, then use command treesit-install-language-grammar install miss parser
