### ISSUE TITLE
在 color-rg 的编辑模式应用修改后的错误行为

### ISSUE THREAD

**Issue by xplutoy** [manateelazycat/color-rg#103]
在使用 color-rg 的过程中发现应用修改的奇怪行为，看了下代码，与 color-rg-apply-changed 用 kill-line 来实现应用修改有关。

1. 如果设置选项 kill-whole-line 为 t ，则应用修改后会删除断行（\n），导致上下两行连在一起
2. 如果删除在 org-mode 的 head line 里面，会把整个 head 及其下面的内容一起删掉

我不太会修改 elisp，有时间可以修复下吗？

**Comment by manateelazycat** [comment]
第一个问题我推送了补丁 https://github.com/manateelazycat/color-rg/commit/1bb68a2bc799ab7c1c35cd491d397bef94e8cfbb

第二个问题欢迎提交补丁， 我很少用 org-mode, 不太想研究 org-mode 的问题。
