### ISSUE TITLE
treesit-buffer-root-node: No available parser for this buffer

### ISSUE THREAD

**Issue by kapmix** [manateelazycat/color-rg#104]
光标落在字符串上面，执行 color-rg-search-input-in-current-file， 出错，
`treesit-buffer-root-node: No available parser for this buffer: #<buffer blink-search.el>`

<img width="660" alt="截屏2024-07-26 09 59 27" src="https://github.com/user-attachments/assets/6ae0da56-4ac9-4d84-9ed4-38fecf1ae687">

**Comment by manateelazycat** [comment]
需要学会配置 treesit https://github.com/manateelazycat/lazycat-emacs/blob/7ad2ca778e3380e9bc6033b4e7576f3636d18862/site-lisp/config/init-treesit.el#L96
