### ISSUE TITLE
color-rg-customized-search displays 0 matches, prevents filtering and navigation

### ISSUE THREAD

**Issue by Tokubara** [manateelazycat/color-rg#105]
The search results of `color-rg-customized-search` display 0 matches (there are actually many results), preventing filtering operations (such as f/F) and navigation via Enter key. As shown in the attached image:

![1f290a34fda6bf7e20bd7c2334e8c8957c463dc5](https://github.com/user-attachments/assets/34933212-d51e-48af-9e99-86720dcbfde9)

When attempting to perform filtering using f/F, it echos:
```
Remove 0 lines not match regexp 'degree'.
```

When trying to navigate by pressing Enter, it displays:
```
color-rg-move-to-column: Search failed: "^\\([1-9][0-9]*\\):\\([1-9][0-9]*\\):"
```

**Comment by manateelazycat** [comment]
我早上试了一下， 是可以的， 请用 emacs -Q 排除一下你自己的配置影响。

**Comment by Tokubara** [comment]
The problem occurred even when I used `emacs -Q`, the version of color-rg is 20240714.170041, and my emacs version is 29.1.90.
![Uploading image.png…]()

**Comment by manateelazycat** [comment]
color-rg-customized-search 的设计为搜索后再自定义搜索用 color-rg-customized-search， 不是一开始就用 color-rg-customized-search

如果你要自定义关键字， 完全可以用 color-rg-search-input 命令手动输入关键字。

color-rg 默认的关键字有 ```rg --no-config --column --color=always -H --heading --max-columns 3000 --no-ignore -g '!node_modules' -g '!dist' -g '!TAGS' -g '!tags' -g '!*~' -U --smart-case -e keyword search-directory```

如果默认都不传入这些关键字， 就无法显示列和关键字高亮，而且会搜索出很多无关的目录内容。
