### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by ChongQing520** [manateelazycat/color-rg#14]
我看代码的时候比较多

是不是可以把buffer的名字改成与key相关的

并用 cur-search 保存调用的 current-buffer，这样就可以在两个buffer之间切换了

可以走的更远一点 ： 一个buffer可以与多个 color-rg 相关

**Comment by manateelazycat** [comment]
一个 buffer 关联 多个 color-rg 的时候, 如果每个 color-rg 都在重构修改内容的时候, 估计会有大范围冲突.

不过你有啥想法, 随时欢迎 PR
