### ISSUE TITLE
Symbol’s function definition is void: s-trim

### ISSUE THREAD

**Issue by ctrl2wei** [manateelazycat/color-rg#19]
I got an error when use color-rg-search-input , it says "Symbol’s function definition is void: s-trim"
I found "s-trim" is a function in s.el (https://github.com/magnars/s.el), but you not require it
maybe should change "s-trim" to "string-trim"?

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/color-rg/commit/4606079ca207b5a7de83c722da343658f54cb187 DONE
