### ISSUE TITLE
Undefined function when call `M-x color-rg-search-input`

### ISSUE THREAD

**Issue by jueqingsizhe66** [manateelazycat/color-rg#21]
Line676:   (or (nth 3 (or state (insert-translated-name-current-parse-state)))

Symbol's function definition is void: insert-translated-name-current-parse-tree!!

**Comment by manateelazycat** [comment]
Sorry, my typo.

Has fixed by https://github.com/manateelazycat/color-rg/commit/db6cacb316e3f1d1bcc5c2ce73cabbecb722dfc3

Thanks for report
