### ISSUE TITLE
How to ignore or exclude some files by regex

### ISSUE THREAD

**Issue by zwpaper** [manateelazycat/color-rg#23]
after using color rg for searching

I want to ignore the testing file like `_test.go`

rg can do this like `--glob=!*_test.go`

but

1. `m` for color-rg looks like not working
2. there is no other to change the rg args

Can u document about this?

---

BTW, Thanks for the great package.

**Comment by manateelazycat** [comment]
@pengpengxp Can you looks this issue ?  
Thanks ;)

**Comment by manateelazycat** [comment]
@zwpaper https://github.com/manateelazycat/color-rg/pull/24

**Comment by pengpengxp** [comment]
Hi zwpaper,
    rg have some redefined globs, you can check it by
```
rg --type-list
```

    color-rg have a function 'color-rg-rerun-change-files' bind in z which will filter searched files with these predefined globs. This function also work If you want to filter by your own glob. For example, just input '*_test.go' will only search 1_test.go, 2_test.go and xxxx. This feature use rg '--type-add' and '--type' arguments, the pesudo command may look like this:
```
rg --type-add custom\:\*_test.go --smart-case --type custom
```

    This function is good. But, can not feed you demand. So I just add a function 'color-rg-rerun-change-exclude-files'. If you run this function in the same situation, the pesudo command may be:
```
rg --type-add custom\:\*_test.go --smart-case --type-not custom
```
    I hope this will help you :)

   BTW, I also add a function 'color-rg-customized-search' which will give you more freedom to customize rg command. Just have a try :)

    All these function is here https://github.com/manateelazycat/color-rg/pull/24 .

**Comment by zwpaper** [comment]
Hi, peng,

Thanks for the great work.

I have tried the feature, there still are 2 part imperfect

1. When using `exclude file` the message prompt show is: `Repeat search in files (default: [ everything ])`. this confused, maybe`Repeat search exclude files (default: [ nothing ])` will be better?
2. When using `customized-search`, `*` has to manually Escape like `\*`, can color-rg handle this?

**Comment by pengpengxp** [comment]
Hi, zwpaper,

    I create a PR for 1 in https://github.com/manateelazycat/color-rg/pull/25. Thank you for the feedback.

   For question 2, If you only want color-rg to include or exclude search files. I thought function color-rg-rerun-change-exclude-files and color-rg-rerun-change-files have handled this.

    For example, if you want to exclude some file like *_test.go, just run color-rg-rerun-change-exclude-files and input "*_test.go" without escape anything.

    Actually, customized-search is for more advanced situation in which you want to use rg in shell command directly. You can add any argument to rg as you like. You can treat this as a shell command. As you see, colorg-rg use \* to Escape * like:
```
rg --type-add custom\:\*.el 
```
   
   If You don't like it, You can also quote it:
```
rg --type-add "custom:*.el"
```
    I have test, it also work.
