### ISSUE TITLE
我提个建议啊

### ISSUE THREAD

**Issue by zhouchongzxc** [manateelazycat/color-rg#31]
应该加上些hook

比如说

在rg搜索完并insert到color-rg-buffer之后

还有就是color-rg-open-file之后

**Comment by manateelazycat** [comment]
请直接说你想要这些接口去做什么，我如果觉得有用，我会加必要的hook。
如果你不说需求，只是说要加各种hook，我就觉得没有必要了，因为hook越多，越不稳定。
