### ISSUE TITLE
搜索结果中奇怪的高亮

### ISSUE THREAD

**Issue by smallzhan** [manateelazycat/color-rg#33]
我这里搜索出来的结果中会有奇怪的高亮, 环境是 doom-emacs. 我研究了一下安装的包,对应去 disable, 但是没找到问题.  表现是会随机出现不规则的色块,如下图所示(在 color-rg.el 中搜索 color-rg), 我 describe-char 看了一下,与正常显示的区别是有一个奇怪的 overlay, 目前还没有其他头绪.
<img width="647" alt="屏幕快照 2019-05-13 19 13 56" src="https://user-images.githubusercontent.com/1635790/57617405-50667b00-75b3-11e9-8f06-7a5983c7649c.png">

**Comment by manateelazycat** [comment]
两条路径：
第一，测试一下 Emacs -Q 有没有问题？如果 Emacs -Q 没有问题，应该就是你配置的问题。
第二， 如果方便，可以发一下你详细的重现方法，我可以帮你看一下。

谢谢反馈

**Comment by smallzhan** [comment]
非常奇怪, emacs -Q 没问题, 我看了下命令行返回的东西,然后发现高亮的两个颜色正好是行号和红色的关键字,  所以我把 color-rg-filter 里面处理 ansi-color 的那两个正则表达式替换的去掉了 (;;Highlight rg matches... 和 ;;Delete all remaining escape sequences 两部分 ), 这样处理之后表现正常了. 关键字是红色,行号是绿色, 和终端表现一致. 但是这样处理之后使用 emacs -Q 启动, 结果里面又都是一堆 ansi-color 字串.   因为我用的 doom-emacs, 重现可以使用类似下面的一个最小的 init.el  (除了 doom 自己定义的核心, 什么都不附加), 所以这个可能是 doom 里面的问题了.  

``` 
   (doom! :input
       :completion
       :ui
       :editor
       :emacs
       :tools
       :lang
       :email
       :app
       :collab
       :config)

**Comment by manateelazycat** [comment]
建议你用二分注释法去查找出问题的配置。

**Comment by smallzhan** [comment]
感谢回复, 找到问题了,  doom-emacs 的 core/core-ui.el 里面有一句 

``` emacs-lisp
(add-hook 'compilation-filter-hook #'doom|apply-ansi-color-to-compilation-buffer) 
```

去掉就好了.
