### ISSUE TITLE
请提供默认快捷键支持

### ISSUE THREAD

**Issue by Qquanwei** [manateelazycat/color-rg#35]
可以方便直接将一组快捷键应用到mode上，或者增加一个 `color-rg-command-map`用来用户自己绑定前缀。

参考projectile的绑定方式
```
 (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
```

**Comment by manateelazycat** [comment]
这个暂时不用了吧，因为 color-rg.el 很多按键的使用场景都不一样，我提供默认按键就会众口难调，与其用自己的习惯导致和用户的全局按键冲突，还不如用户自己绑定这些全局按键。
