### ISSUE TITLE
使用某些函数需要加载一些外部库。

### ISSUE THREAD

**Issue by ctrl2wei** [manateelazycat/color-rg#36]
**which-function** （需要加载 which-func.el）
https://github.com/manateelazycat/color-rg/blob/1ec0b2ae60aa9311ea78ec918f83998325ebb874/color-rg.el#L1399

**-if-let**  （需要加载 dash.el)
https://github.com/manateelazycat/color-rg/blob/1ec0b2ae60aa9311ea78ec918f83998325ebb874/color-rg.el#L1095

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/color-rg/commit/7f54c4cde6a87f75a5cde41b61fd7e73efba1a85
已经修复了，谢谢反馈。
