### ISSUE TITLE
怎么和swiper一起用

### ISSUE THREAD

**Issue by QiangF** [manateelazycat/color-rg#38]
swiper比isearch好用，怎么把isearch-toggle-color-rg改成适合swiper啊

    (defun swiper-toggle-color-rg ()
    (interactive)
    (color-rg-search-input isearch-string))

**Comment by manateelazycat** [comment]
我不用swiper，我也不想给我不用的东西开发功能，当然如果你有能力的话，欢迎贡献补丁

**Comment by QiangF** [comment]
还在努力向大师们学习，提了一个swiper的issue，呵呵
https://github.com/abo-abo/swiper/issues/2122
