### ISSUE TITLE
color-rg-apply-changed 在最新的 emacs --HEAD 中无效

### ISSUE THREAD

**Issue by smallzhan** [manateelazycat/color-rg#40]
平台： MacOS, emacs 27.0.50

emacs 安装方式： 
`brew install emacs-plus --HEAD --with-xwidgets --with-jansson --without-spacemacs-icon`
xwidgets 补丁使用了 https://github.com/d12frosted/homebrew-emacs-plus/pull/149 

症状： 
`emacs -q` 启动， 然后随意找个文件， `color-rg-search-input-in-current-file`  搜索，在搜索结果中，e 进入 edit 模式，编辑后通过 `C-c C-c` 发送 `color-rg-apply-changed` 命令，Minibuffer 提示 `Text is read only`. 
然后打开的文件变成了 read-only 模式， 此时 emacs 也无法退出， `C-x C-c` 提示 `Text is read only`。

emacs 26.2 中上述操作表现正常。

**Comment by manateelazycat** [comment]
不支持开发版，开发版太多bug
