### ISSUE TITLE
color-rg-search-input-in-project 是怎么使用的？

### ISSUE THREAD

**Issue by e190** [manateelazycat/color-rg#41]
直接 给 color-rg-search-input-in-project 绑定按键，是不行的。请问这个怎么使用？

**Comment by manateelazycat** [comment]
直接绑定按键后，按快捷键后输入搜索的字符串就可以了。

请用emacs -Q 启动 Emacs 排除问题

**Comment by e190** [comment]
![图片](https://user-images.githubusercontent.com/39932163/66015449-2c291d80-e505-11e9-9969-2cb7d068dd38.png)
根本就没有出现输入框，直接就报错了

**Comment by manateelazycat** [comment]
请阅读README的安装方法

**Comment by e190** [comment]
![图片](https://user-images.githubusercontent.com/39932163/66128393-57545f80-e620-11e9-9f13-a81318511fc6.png)
我这样使用也是出错。

command-execute: Wrong type argument: commandp, color-rg-search-input-in-projcet

**Comment by manateelazycat** [comment]
color-rg-search-project 绑定这个命令试一下

**Comment by e190** [comment]
> 
> 
> color-rg-search-project 绑定这个命令试一下

这个命令是没有问题的，我就奇怪，为什么 color-rg-search-input-in-projcet 不能绑定？
(defalias 'color-rg-search-input-in-project 'color-rg-search-project)
defalias 定义后就不行？
