### ISSUE TITLE
搜索完成后，按r全局替换无效

### ISSUE THREAD

**Issue by Gaeric** [manateelazycat/color-rg#44]
原生的Emacs环境下，在搜索完成后的结果中，使用r全局替换无效；
OS：ArchLinux
Version: 28.0.50
color-rg: 1ad93ce9b1ad0c636a977ed404df00a380e1b600

是我的操作中少了什么步骤吗？
或者还需要其它的什么信息？

**Comment by manateelazycat** [comment]
r表示进入替换，按 y 或者 n 来表示是否替换当前行，按！替换所有。
这个和Emacs的行为一致，不是bug.
