### ISSUE TITLE
windows 平台进行搜索报错：split-string: Wrong type argument: stringp, nil 

### ISSUE THREAD

**Issue by tfighting** [manateelazycat/color-rg#45]
具体问题我放张截图：
![Snipaste_2020-03-30_09-25-43](https://user-images.githubusercontent.com/48683803/77870194-62a4e280-7273-11ea-87fe-09e59174cfb8.png)

**Comment by manateelazycat** [comment]
backtrace最顶部的信息也截图一下，最顶部那一行比较关键，谢谢。

**Comment by tfighting** [comment]
![Snipaste_2020-03-30_09-25-43](https://user-images.githubusercontent.com/48683803/77883060-ede2a000-7294-11ea-841b-c9f7d00bd9a6.png)

**Comment by manateelazycat** [comment]
你直接截图整个桌面吧，这张图和第一章有啥区别？

**Comment by tfighting** [comment]
![Snipaste_2020-03-30_14-46-32](https://user-images.githubusercontent.com/48683803/77883233-444fde80-7295-11ea-943d-5bb91904bb8e.png)

**Comment by manateelazycat** [comment]
你执行一下 (shell-command-to-string (concat (executable-find "rg") " --type-list")) 这个命令

然后把输出结果给我一下。

**Comment by tfighting** [comment]
能出结果，但是乱码
![Snipaste_2020-03-30_15-04-52](https://user-images.githubusercontent.com/48683803/77884542-d822aa00-7297-11ea-9c0f-b9ef175fd3c9.png)

**Comment by tfighting** [comment]
在cmd可以正常输出
![Snipaste_2020-03-30_15-09-31](https://user-images.githubusercontent.com/48683803/77884885-8595bd80-7298-11ea-9033-d5868cb23dd9.png)

**Comment by manateelazycat** [comment]
我怎么感觉是你的系统编码被你折腾坏了，和color-rg没有关系。

**Comment by manateelazycat** [comment]
系统编码的问题，如果你以前可以，现在不行，应该是系统的问题。

color-rg.el 最近很少更新。
