### ISSUE TITLE
'color-rg-jump-prev-keyword' got stuck in some line(middle?)

### ISSUE THREAD

**Issue by liuyinz** [manateelazycat/color-rg#54]
![Kapture 2021-01-16 at 00 52 37](https://user-images.githubusercontent.com/35212403/104756284-961b1400-5796-11eb-825f-40bf605fe954.gif)

**Comment by liuyinz** [comment]
Macos Big Sur , both emacs 27 and 28 have the same problem. Only load exec-path-from-shell.el and color-rg.el

**Comment by manateelazycat** [comment]
> Macos Big Sur , both emacs 27 and 28 have the same problem. Only load exec-path-from-shell.el and color-rg.el

Can you send your search directories to me?

I can't reproduce your problem.

**Comment by liuyinz** [comment]
As you said, I try another directory , everything is fine.... I will check what's wrong in the first directory.

**Comment by liuyinz** [comment]
Solved by d7be8215a75e553f682f12659eebfe2c853d5d07
