### ISSUE TITLE
color-rg 搜索 org 中的代码块出现乱码

### ISSUE THREAD

**Issue by patrolli** [manateelazycat/color-rg#56]
如图
![image](https://user-images.githubusercontent.com/25717445/107600066-97d4dc00-6c5d-11eb-9eb8-f98378e50fbd.png)
我希望搜索文件中的 hugo 关键词，但是当这个关键词出现在 org 的代码块里面时，搜索就会出现这样的结果。奇怪的是，搜索代码块有些其他内容时不会出错。

我用 emacs -Q 也进行了测试，同样存在这个问题：
![image](https://user-images.githubusercontent.com/25717445/107600229-192c6e80-6c5e-11eb-92af-8c96d55196f0.png)

测试文件在：https://drive.google.com/file/d/1G8oRxwqWMLS5lgzS2SC8T7BCMJdlNsKq/view?usp=sharing

使用 `color-rg-search-input-in-current-file` 搜索关键词 hugo 就会出现这个问题

**Comment by manateelazycat** [comment]
你是系统编码问题

**Comment by patrolli** [comment]
> 你是系统编码问题

似乎不是编码的问题。我找到上面这段内容的问题了，去掉文件中的 `# 开启本地服务，输入 127.0.0.1:1003` 这个注释后，再搜索 hugo 就不会有问题。后面我又测试了下，发现只要一行里有 `# ip+端口`，比如 `xxx # 127.0.0.1:1000` 这样的内容，再去搜索这一行的其他文字，就会出现这样的问题。您那边不会出现这个问题吗？

**Comment by manateelazycat** [comment]
> > 你是系统编码问题
> 
> 似乎不是编码的问题。我找到上面这段内容的问题了，去掉文件中的 `# 开启本地服务，输入 127.0.0.1:1003` 这个注释后，再搜索 hugo 就不会有问题。后面我又测试了下，发现只要一行里有 `# ip+端口`，比如 `xxx # 127.0.0.1:1000` 这样的内容，再去搜索这一行的其他文字，就会出现这样的问题。您那边不会出现这个问题吗？

不好意思，今天测试了一下确实有问题，只要有 :1000 这样的内容就会触发，但是目前还知道原因。
如果你有一定的Elisp功底，可以用命令 toggle-debug-on-error 打开错误堆栈，欢迎PR

**Comment by patrolli** [comment]
这个问题似乎是 ansi-color 没有正确渲染导致的，触发这个 bug 的条件就是 `# number: number` 这样的字符串。在 color-rg 搜索结果的 buffer 中，使用 `(ansi-color-apply-on-region (point-min) (point-max))` 重新渲染 color-rg 的 buffer，这个问题就没有了。但我还不知道怎么加在 color-rg 的代码里面，只有在外部使用命令重新渲染 color-rg 的 buffer.

**Comment by patrolli** [comment]
> 这个问题似乎是 ansi-color 没有正确渲染导致的，触发这个 bug 的条件就是 `# number: number` 这样的字符串。在 color-rg 搜索结果的 buffer 中，使用 `(ansi-color-apply-on-region (point-min) (point-max))` 重新渲染 color-rg 的 buffer，这个问题就没有了。但我还不知道怎么加在 color-rg 的代码里面，只有在外部使用命令重新渲染 color-rg 的 buffer.

**Comment by patrolli** [comment]
> > > 你是系统编码问题
> > 
> > 
> > 似乎不是编码的问题。我找到上面这段内容的问题了，去掉文件中的 `# 开启本地服务，输入 127.0.0.1:1003` 这个注释后，再搜索 hugo 就不会有问题。后面我又测试了下，发现只要一行里有 `# ip+端口`，比如 `xxx # 127.0.0.1:1000` 这样的内容，再去搜索这一行的其他文字，就会出现这样的问题。您那边不会出现这个问题吗？
> 
> 不好意思，今天测试了一下确实有问题，只要有 :1000 这样的内容就会触发，但是目前还知道原因。
> 如果你有一定的Elisp功底，可以用命令 toggle-debug-on-error 打开错误堆栈，欢迎PR

这个问题似乎是 ansi-color 没有正确渲染导致的，触发这个 bug 的条件就是 `# number: number` 这样的字符串。在 color-rg 搜索结果的 buffer 中，使用 `(ansi-color-apply-on-region (point-min) (point-max))` 重新渲染 color-rg 的 buffer，这个问题就没有了。但我还不知道怎么加在 color-rg 的代码里面，只有在外部使用命令重新渲染 color-rg 的 buffer.
