### ISSUE TITLE
evil-mode compatibility issue 

### ISSUE THREAD

**Issue by digitive** [manateelazycat/color-rg#58]
This extension is really cool however it doesn't work well in my Emacs. I have evil-mode and evil-collection installed. The search works fine but I cannot visit the file from the result buffer. RET key just keep moving to next line.

A similar extension called [deadgrep](https://github.com/Wilfred/deadgrep) had the similar issue but solved by this commit in evil-collection. [dab8f383](https://github.com/emacs-evil/evil-collection/commit/dab8f3836e8939b1b32cf2ed5d381ae0fdd8fd83)

I hope this bug can be fixed. Thanks for the awesome work!

**Comment by robertzhouxh** [comment]
+1

**Comment by manateelazycat** [comment]
Sorry, I don't use evil, can't help you.

PR are welcome.
