### ISSUE TITLE
请问 color-rg 的第一行命令提示行可以设置成折行吗？有时候分割窗口之后看不见后面的语句了

### ISSUE THREAD

**Issue by mgpanpan** [manateelazycat/color-rg#63]
感谢大佬的这个 package，很好用！

我想问一下首行 ([COLOR-RG] Search ...) 这里可以设置成自动折行 (line-wrap) 吗？分割窗口之后，一般这个后面的提示语句就都看不见了。

如下面图里面，Edit e 后面还有很多提示命令

![image](https://user-images.githubusercontent.com/4384206/163511015-22ba5dd5-5a47-4bdc-9868-1c6895fd9e71.png)

感谢！

**Comment by manateelazycat** [comment]
现在用的head-line，不知道会不会换行

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/color-rg/issues/63

**Comment by mgpanpan** [comment]
感谢修改！

但是我试了一下，好像 head-line 还是不能折行，是我哪里没有设置对么？我用 emacs -Q 然后把 color-rg 加载进来，也还是这样

![image](https://user-images.githubusercontent.com/4384206/163671675-903ae86e-e9be-4314-acb1-c308f47b6963.png)

**Comment by manateelazycat** [comment]
我只是减少字符串，减少宽度，你的屏幕咋这么小呀

**Comment by mgpanpan** [comment]
哦哦，怪不得，周末用自己的小本试的，那我明白了，谢谢😂
