### ISSUE TITLE
`(cdr project)` in `color-rg-project-root-dir` is no more a string

### ISSUE THREAD

**Issue by theFool32** [manateelazycat/color-rg#65]
It seems `(cdr project)` in function [`color-rg-project-root-dir`](https://github.com/manateelazycat/color-rg/blob/f774d83e24ced632c6d94d7d729fccc1dd2c833c/color-rg.el#L1203) is no more a string, which causes the function `expand-file-name` failed.

A workaround can be
```elisp
(expand-file-name (if (fboundp 'project-root)
                                       (project-root project)
                                     (cdr project)))
```
from [`doom-modeline--project-root`](https://github.com/seagle0128/doom-modeline/blob/7d8eb7c44087a62d8dd6e8ba1afc26facd914fbc/doom-modeline-core.el#L1250).

**Comment by manateelazycat** [comment]
Fixed, thanks for report.
