### ISSUE TITLE
go代码里在行内最后一个字符执行搜索会报错

### ISSUE THREAD

**Issue by liguangsheng** [manateelazycat/color-rg#66]
![image](https://user-images.githubusercontent.com/8074650/172321171-ddc193a1-62ac-484b-ab10-83c77ed69575.png)

![image](https://user-images.githubusercontent.com/8074650/172321238-ea5aad13-cd6d-4f67-87ad-70fb0b1118ea.png)

`(parse-partial-sexp (point) point)` 改成 `(parse-partial-sexp (point) (max (point) point))`或许能解决这个问题？

**Comment by manateelazycat** [comment]
给一个测试文本吧。

**Comment by liguangsheng** [comment]
```
package main

var (
	a = 0
)

const (
	b = 0
)

import (
	"fmt"
)

func main() {
	fmt.Println("Hello World!")
}
```

cursor在package, var, const, import的时候都可以复现

**Comment by manateelazycat** [comment]
已经修复了。
