### ISSUE TITLE
使用 r 键尝试 replace, 并取消后，显示有错。

### ISSUE THREAD

**Issue by zw963** [manateelazycat/color-rg#68]
假设现在用 `BrightnessChangedEvent` 搜索项目，得到三个文件内的若干结果。

尝试按下 `r` 做替换， 替换为 BrightnessChangedEvent123

此时 minibuffer 提示如下 （见截图）

![image](https://user-images.githubusercontent.com/549126/173238761-002b0fa3-1ce2-4887-b9a1-1d3bfe61fe1e.png)

按下回车执行替换，此时 minibuffer 可能因为最近改了配置原因，只是显示一个 `r-`, （见截图）

![image](https://user-images.githubusercontent.com/549126/173239171-340297fb-e4c3-4d36-85c7-13b6027421e9.png)

 刚开始并未理解是怎么回事儿，因此我会 C-g 取消掉。

然后再次按下 r 尝试替换时，显示如下： （见截图）

![image](https://user-images.githubusercontent.com/549126/173239219-ef30422b-3936-4929-b36c-078ec39c7dc1.png)

这个显示是错的，因为文件中内容并没有完成替换。

**Comment by manateelazycat** [comment]
r- 的问题，请用 `emacs -Q` 自己排查一下你配置的问题， 我不知道你的配置文件是啥问题。

r按键回车以后，会对 color-rg 的 buffer 做替换高亮， 你需要按 !、y、n 按键进行替换后， color-rg 才会写入替换的内容。

**Comment by zw963** [comment]
> r按键回车以后，会对 color-rg 的 buffer 做替换高亮， 你需要按 !、y、n 按键进行替换后， color-rg 才会写入替换的内容。

这个我知道，可能我没描述清楚问题，我的意思是，我根本没有执行替换，因为我 C-g 取消了。但是 minibuffer 显示为：

Replace "BrightnessChangedEvent123" all matchs with ...

正确的显示应该是：

Replace "BrightnessChangedEvent" all matchs with ...

**Comment by manateelazycat** [comment]
> > r按键回车以后，会对 color-rg 的 buffer 做替换高亮， 你需要按 !、y、n 按键进行替换后， color-rg 才会写入替换的内容。
> 
> 这个我知道，可能我没描述清楚问题，我的意思是，我根本没有执行替换，因为我 C-g 取消了。但是 minibuffer 显示为：
> 
> Replace "BrightnessChangedEvent123" all matchs with ...
> 
> 正确的显示应该是：
> 
> Replace "BrightnessChangedEvent" all matchs with ...
> 
> 因为 buffer 里面的内容还是 BrightnessChangedEvent 而不是 BrightnessChangedEvent123

我看懂你的意思了，但是我重现不了，所以你需要 `emacs -Q` 先排除一下问题， 确认是 color-rg 的问题再来报 bug.

**Comment by zw963** [comment]
奇怪，emacs -Q 我还是可以重现啊

![image](https://user-images.githubusercontent.com/549126/173246455-4db7ce16-cffc-432a-90f2-a97ffee0d940.png)

下面是重现的步骤：

1.  随便找个什么东西搜索
2. 在搜索页面按下 TAB 若干次，光标在某个匹配结果之上
3.  按下 r 键，此时提示： Replace "foo" all matches with: 
4. 将匹配结果改为 foo123, 即：Replace "foo" all matches with: foo123
5. 回车后，可以看到右侧高亮显示匹配内容，左下角 minibuffer 有个 r- , 大概下面截图的样子。
![image](https://user-images.githubusercontent.com/549126/173246635-eeccf846-f905-417a-8d7e-3220ece8bf9b.png)
 除非你把鼠标点到 minibuffer 里面去，否则，并不会提示  !、y、n  这些快捷键。（这可能是另外一个问题）
6. 此时光标在搜索结果页面了，但我不想替换了，C-g 退出当前替换操作。
7.  我又想替换了，再次按下 r
8.  上面截图的结果出现。

**Comment by manateelazycat** [comment]
确实没法重现

**Comment by zw963** [comment]
> 确实没法重现

好的，多谢，明天编译个最新版本的 Emacs 28 我再试下
