### ISSUE TITLE
先按下 u (color-rg-unfilter), 然后再按下 L 或 R 出错。

### ISSUE THREAD

**Issue by zw963** [manateelazycat/color-rg#69]
下面是出错信息：

```
Debugger entered--Lisp error: (wrong-type-argument consp nil)
  color-rg-rerun()
  color-rg-rerun-literal()
  funcall-interactively(color-rg-rerun-literal)
  #<subr command-execute>(color-rg-rerun-literal nil nil nil)
  ad-Advice-command-execute(#<subr command-execute> color-rg-rerun-literal)
  apply(ad-Advice-command-execute #<subr command-execute> color-rg-rerun-literal)
  command-execute(color-rg-rerun-literal)

```

重现：

1.  随便搜索个关键字，得到若干结果。（此时结果全部为同一文件类型）
2.  按一下 u, 因为只有一个文件类型，而且之前也没有通过 x 或 X 过滤过，此时没有任何提示。
3.  按下 L 或 R, 出现上述错误。

**Comment by manateelazycat** [comment]
`emacs -Q` 排查你的配置文件，我无法重现。

**Comment by zw963** [comment]
这个我在 emacs -Q 的情况下也可以重现。

请看输出：

backtrace

```
Debugger entered--Lisp error: (wrong-type-argument consp nil)
  color-rg-rerun()
  color-rg-rerun-literal()
  funcall-interactively(color-rg-rerun-literal)
  command-execute(color-rg-rerun-literal)
```

搜索结果页面：

```
-*- mode: color-rg; default-directory: "~/test_project/lib/" -*-
color-rg started at Mon Jun 13 01:33:13

rg --column --color=always -H --heading --max-columns 3000 --no-ignore -g "!*~" -g "!#*#" -g "!*.min.*" -g "!TAGS" -g "!tags" -g "!.git/" -g "!node_modules" -g "!dist" -g "!*.log"  --smart-case -e BrightnessChangedEvent /home/zw963/test_project/
/home/zw963/test_project/lib/app.dart
83:35:        Application.eventBus.fire(BrightnessChangedEvent(
110:20:    listenEventBus<BrightnessChangedEvent>((event) {

/home/zw963/test_project/lib/pages/my/my_themes_page.dart
41:45:                  Application.eventBus.fire(BrightnessChangedEvent(
71:45:                  Application.eventBus.fire(BrightnessChangedEvent(

/home/zw963/test_project/lib/events/brightness_changed_event.dart
3:7:class BrightnessChangedEvent {
7:3:  BrightnessChangedEvent({

color-rg finished (6 matches found) at Mon Jun 13 01:33:13
```

我上面描述的也不够准确，我更新下：


    1. 随便搜索个关键字，得到若干结果。（此时结果全部为同一文件类型）
    2. 按下 TAB, 跳转到第一条结果上
    3. 按一下 u, 因为只有一个文件类型，而且之前也没有通过 x 或 X 过滤过，此时没有任何提示。
    4. 按下 L
    5. 回车再次搜索，出现上述错误。

事实上不止是 L, 所有需要 rerun 的命令，都会出错。

**Comment by manateelazycat** [comment]
> 这个我在 emacs -Q 的情况下也可以重现。
> 
> 请看输出：
> 
> backtrace
> 
> ```
> Debugger entered--Lisp error: (wrong-type-argument consp nil)
>   color-rg-rerun()
>   color-rg-rerun-literal()
>   funcall-interactively(color-rg-rerun-literal)
>   command-execute(color-rg-rerun-literal)
> ```
> 
> 搜索结果页面：
> 
> ```
> -*- mode: color-rg; default-directory: "~/test_project/lib/" -*-
> color-rg started at Mon Jun 13 01:33:13
> 
> rg --column --color=always -H --heading --max-columns 3000 --no-ignore -g "!*~" -g "!#*#" -g "!*.min.*" -g "!TAGS" -g "!tags" -g "!.git/" -g "!node_modules" -g "!dist" -g "!*.log"  --smart-case -e BrightnessChangedEvent /home/zw963/test_project/
> /home/zw963/test_project/lib/app.dart
> 83:35:        Application.eventBus.fire(BrightnessChangedEvent(
> 110:20:    listenEventBus<BrightnessChangedEvent>((event) {
> 
> /home/zw963/test_project/lib/pages/my/my_themes_page.dart
> 41:45:                  Application.eventBus.fire(BrightnessChangedEvent(
> 71:45:                  Application.eventBus.fire(BrightnessChangedEvent(
> 
> /home/zw963/test_project/lib/events/brightness_changed_event.dart
> 3:7:class BrightnessChangedEvent {
> 7:3:  BrightnessChangedEvent({
> 
> color-rg finished (6 matches found) at Mon Jun 13 01:33:13
> ```
> 
> 我上面描述的也不够准确，我更新下：
> 
> ```
> 1. 随便搜索个关键字，得到若干结果。（此时结果全部为同一文件类型）
> 2. 按下 TAB, 跳转到第一条结果上
> 3. 按一下 u, 因为只有一个文件类型，而且之前也没有通过 x 或 X 过滤过，此时没有任何提示。
> 4. 按下 L
> 5. 回车再次搜索，出现上述错误。
> ```
> 
> 事实上不止是 L, 所有需要 rerun 的命令，都会出错。

这个步骤可以重现，已经修了。
