### ISSUE TITLE
[问题] 使用 color-rg 搜索，并且使用 TAB 依次打开结果查看，如果找到了感兴趣的文件，此时希望编辑这个并退出 color-rg

### ISSUE THREAD

**Issue by zw963** [manateelazycat/color-rg#71]
color-rg 最近用的很好，不过有个问题还是挺困扰我。

下面是 reproduce:

例如，当前，我在 A 页面，

1. 然后打开 color-rg 搜索 "Mobile_GroupMembersPage", 然后找到了期望的结果。
2.  我用 TAB 切换到那个搜索结果，让 buffer 内容显示出来
3. 然后我按下回车，光标切换到这个页面，假设叫做 B 页面

然后这个时候，我的目的其实是： “退出 color-rg window, 并且在新的搜索到 B 页面继续编辑“, 
我最开始的做法是，执行命令 ”color-rg-quit", 这个肯定是不行的，因为又回到了 A 页面。

所以我通常的做法是： C-x 1, 让当前 buffer 直接最大化，但是这个似乎并不是正确的解决办法，
因为 color-rg 并未退出，我真正的目的是，color-rg-open-file-and-stay-then-quit-color-rg

当然，原来的 RET 的  color-rg-open-file-and-stay 还是很有用的，我可以随时通过 color-rg-back 返回搜索页面，继续查找。
我只是希望有另一个 defun, 例如，绑定到 C-j，可以打开搜索结果页面，并且完全退出 color-rg.(关闭 color-rg window）

**Comment by manateelazycat** [comment]
我遇到你这种情况就直接把 color-rg 窗口杀掉就好， 如果后续你还想继续搜索，我建议直接隐藏 color-rg 窗口， 以后可以切换回来继续操作。

**Comment by zw963** [comment]
> 我遇到你这种情况就直接把 color-rg 窗口杀掉就好， 如果后续你还想继续搜索，我建议直接隐藏 color-rg 窗口， 以后可以切换回来继续操作。

对对，我刚刚想了下，这的确是个伪名题，反正 color-rg 已经搜索完了，就是一个 window 而已，干掉这个 window 的确达到了我的目的，而且这种情况下，还有个好处，任何时候，再调用 color-rg-back， 其实就相当于重新搜索上一次的 pattern, 挺好的。

**Comment by manateelazycat** [comment]
> > 我遇到你这种情况就直接把 color-rg 窗口杀掉就好， 如果后续你还想继续搜索，我建议直接隐藏 color-rg 窗口， 以后可以切换回来继续操作。
> 
> 对对，我刚刚想了下，这的确是个伪名题，反正 color-rg 已经搜索完了，就是一个 window 而已，干掉这个 window 的确达到了我的目的，而且这种情况下，还有个好处，任何时候，再调用 color-rg-back， 其实就相当于重新搜索上一次的 pattern, 挺好的。
> 
> 还有个好处，如果希望引用搜索结果处的代码的话，找到了，复制了，直接 color-rg-quit, 就又回到最开始的地方，挺好。

如果要插入搜索处的那行代码，可以直接按 i （color-rg-insert-current-line）, 它会把复制、退出、插入三个功能一起做了。

**Comment by manateelazycat** [comment]
> > 如果要插入搜索处的那行代码，可以直接按 i （color-rg-insert-current-line）, 它会把复制、退出、插入三个功能一起做了。
> 
> 这个操作其实我不得要领，请指教。
> 
> 假设当前文件有一行是这个样子：
> 
> ```
> color: AppMoreTheme.of(context).listThemeData.backgroundColor,
> ```
> 
> 然后，我使用选区高亮 `AppMoreTheme`, 开始搜索。（离开前光标在 .of 的前面)
> 
> 假设我找到了我想要的结果，并且使用 TAB 切换到搜索结果之上，它是这个样子。
> 
> ```
>             primary: AppMoreTheme.of(context).quoteBGColor,
> ```
> 
> 然后我输入 i, 结果就是下面这个样子。
> 
> color: AppMoreTheme primary: AppMoreTheme.of(context).quoteBGColor,.of(context).listThemeData.backgroundColor,
> 
> 我猜这应该不是你讲的使用场景吧？ 是不是一步我的操作方式和您预期的不一样？

我说的是插入搜索结果的整行。
