### ISSUE TITLE
是否考虑加一个 color-rg-rerun-in-project 函数？

### ISSUE THREAD

**Issue by zw963** [manateelazycat/color-rg#76]
我目前用 color-rg 的方式和 VSCode 相同，一个全局快捷键绑定 color-rg-search-input-in-project.

这有个问题，有时候结果的确太多，而且我得配置不少 color-rg-search-ignore-rules.

看你 blog 里，说你常用的是  color-rg-search-input, 这个也挺好的，也可以用 o 在上一级目录搜索。

但是如果可以一个键，从 color-rg-search-input 直接切换到 color-rg-rerun-in-project，就更好了。

这样的话，我可以全局默认为  color-rg-search-input, 如果找不到，再选择向上或直接项目内搜索了。

有兴趣的话，我可以晚点尝试提个 PR.

**Comment by manateelazycat** [comment]
可以啊， 这个功能肯定不错， 欢迎PR
