### ISSUE TITLE
color-rg在win10下当前目录搜索失败

### ISSUE THREAD

**Issue by ajaxxor** [manateelazycat/color-rg#84]
我尝试M+x 运行color-rg-search-symbol，不管是搜索中文还是英文，都没有任何结果。
我把出错的rg命令复制出来，
`rg --column --color=always -H --heading --max-columns 3000 --no-ignore -g '!node_modules' -g '!dist' --smart-case --type org -e "test" "c:/Users/Administrator/.emacs.d/"`
在cmd里运行结果和在emacs里运行一样。
测试了几遍以后，发现是
`-g '!node_modules' -g '!dist'`
的问题。
去掉这两个（setq color-rg-search-ignore-rules ""）以后，color-rg-search-symbol-with-type能够正常在当前目录搜索。
我的问题是
1. 这两个参数的含义是什么，去掉之后会对color-rg-search-symbol-with-type有影响吗（虽然它当前正常运行），比如遗漏一些文件
2. 我能 setq color-rg-search-ignore-rules "" 使用color-rg吗
不太了解rg，谢谢。

**Comment by manateelazycat** [comment]
这两个参数的目的就是不要搜索 node_modules 和 dist 着两个目录， 这两个目录下有大量的文件， 一旦搜索会导致搜索速度极慢。

应该是 windows 引号转义的问题， 不是参数的问题。

我不用 windows， 目前帮不到你。
