### ISSUE TITLE
Color-rg cannot show correct result on Windows 10

### ISSUE THREAD

**Issue by EndlessPeak** [manateelazycat/color-rg#87]
在windows10上emacs内搜索，显示无搜索结果，linux上可以正确显示搜索结果。
1. 使用`color-rg`窗口中生成的命令，在命令行执行可以正确显示搜索结果。
2. 注释掉 `encoding` 部分的代码，情况没有变化。
3. `setq color-rg-search-ignore-rules nil`，情况没有变化。
以上2-3的测试在命令行中均能得到正确的结果。
猜想是否是由于windows上rg返回的查询内容中，rg默认把路径后半部分（相对路径）设置成"\\"，而前半部分（文件所在的绝对路径）由color-rg插件给出的是"/"，导致color-rg无法正确获得rg搜索的结果？我比对相同的搜索命令，在windows和linux上返回的结果除此之外没有其他的不同。

**Comment by EndlessPeak** [comment]
我在 `color-rg-search-input` 函数前加了一个函数以将路径中所有的前向斜杠"/"替换成后向斜杠"\\"
```
(defun replace-forward-slash-with-backward-slash (directory)
  "Replace all forward slashes with backslashes in DIRECTORY."
  (replace-regexp-in-string "/" "\\\\" directory))
(defun color-rg-search-input (&optional keyword directory globs)
  (interactive) 
  (setq directory (replace-forward-slash-with-backward-slash directory))
  ;;其他代码
```
这样得到的命令同样可以在命令行执行得到正确的结果，但在color-rg的buffer中报错是：
rg --column --color=always -H --heading --max-columns 3000 --no-ignore -g '!node_modules' -g '!dist' --smart-case -e "dir" "c:\Users\ASUS\.emacs.d\elpa\color-rg\"
c:\Users\ASUS\.emacs.d\elpa\color-rg": 文件名、目录名或卷标语法不正确。 (os error 123)

我注意到它报错的路径的前面缺少了一个引号，但生成的命令是不缺少这个引号的，我在想如果解决这个问题，是否就能在buffer里得到正确的结果了。您是否能给予一点帮助，感激不尽。

**Comment by EndlessPeak** [comment]
好吧，经过测试，windows中即使路径由正斜杠改为反斜杠甚至双反斜杠以确保rg的输出路径中的斜杠统一，在color-rg的buffer中仍然不能得到正确的结果，而上述三种斜杠的命令在windows terminal命令行中都可以得到结果，真是奇怪。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/color-rg/issues/84
