### ISSUE TITLE
While searching in dired mode, occurs "No such file or directory" error

### ISSUE THREAD

**Issue by hsingko** [manateelazycat/color-rg#88]
command:

```shell
rg --column --color=always -H --heading --max-columns 3000 --no-ignore -g '!node_modules' -g '!dist' --smart-case -e tags "~/Documents/"
```

command didn't expand `~` to home directory path, because it was quoted. 

In the dired buffer, the default-directory is shown as `~/Documents` instead of the complete path `/home/user/Documents`.

**Comment by manateelazycat** [comment]
i don't use dired

pr are welcome
