### ISSUE TITLE
color-rg will modify file automatically

### ISSUE THREAD

**Issue by pengpengxp** [manateelazycat/color-rg#9]
If I use `color-rg-jump-next-keyword' `color-rg-jump-prev-keyword' and `color-rg-open-file', color-rg will modify the corresponding buffer.

Not occur everytime. It's occasionally.

**Comment by manateelazycat** [comment]
@pengpengxp  Has fixed by https://github.com/manateelazycat/color-rg/commit/918ad23373e8d93647f55c4e92c6f70a23c5704f
