### ISSUE TITLE
搜不出东西，但是命令行直接执行能搜索到

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/color-rg#92]
如图，把命令直接复制出来执行就有结果
![image](https://github.com/manateelazycat/color-rg/assets/97490782/95c80cf8-b4a7-4071-bda7-cf7f05caedda)

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/color-rg/issues/84

是这个 issue 的问题， 你看看 Windows 上能否写个补丁来修正上面的 issue 问题？

如果能修正的话， 以后就不会因为这个问题重复坑到别人了， 因为我没有windows用于测试， 所以没有打补丁。

**Comment by heheda123123** [comment]
噢， 跟他这个issue的问题是一样的，我截图里能搜到结果是因为用的powershell，换成cmd就搜不出结果了
已经提了pr，加个powershell前缀就可以了

**Comment by manateelazycat** [comment]
已经合并，感谢补丁

**Comment by ltylty** [comment]
最新的代码中。 提取了一个参数  color-rg-command-prefix  。
需要加上  
(setq color-rg-command-prefix "powershell")
