### ISSUE TITLE
Idea: Support `ripgrep` 's `-A`, `-B` and `-C` option

### ISSUE THREAD

**Issue by eval-exec** [manateelazycat/color-rg#95]
Hello,

I want to express my gratitude for your amazing color-rg project.

I noticed that ripgrep has the following options: `--after-context`, `--before-context`, and `--context`. These options allow for displaying more contextual information in the search results.
```bash
$ rg -h | grep  context
    -A, --after-context <NUM>                    Show NUM lines after each match.
    -B, --before-context <NUM>                   Show NUM lines before each match.
    -C, --context <NUM>                          Show NUM lines before and after each match.
```

It would be wonderful if color-rg could support these options as well, along with the ability to customize the context number in the result buffer of color-rg-mode.

If you find this idea appealing, I would be delighted to submit a pull request. :heart_decoration:

**Comment by manateelazycat** [comment]
color-rg not support multi-line, pr are welcome.

**Comment by manateelazycat** [comment]
@eval-exec Hi, I have push commit https://github.com/manateelazycat/color-rg/commit/bc44a72a766728966a9625fcf1193e39df8d8d13 to fixed this.
