### ISSUE TITLE
Publish on MELPA and/or Non-GNU ELPA (prefer both)

### ISSUE THREAD

**Issue by hab25** [manateelazycat/color-rg#97]
Fetching from source works for me, but I hold the opinion that this project being available in an ELPA gives me and others the following advantages:

- Users are more accustomed and typically face less immediate friction when fetching from an ELPA. This usually results in more users. More users usually means more bug reports and more feature requests. This tends to result in better software.

- If this repository becomes compromised with malware, there is an additional way of taking access to the repository down. I.e., besides reporting to GitHub, one can report to the ELPA's maintainers. Either one of these organizations taking action will likely result in the compromised version of the project no longer being available on the ELPA. A user that is fetching from ELPA gets to benefit from the faster of the two, instead of only the repository hosting provider.

- In case this project archives this location and moves to another location (e.g., GitLab), the project's then-maintainer will likely forget to update the ELPA's "recipe" (MELPA terminology) less often than they forget to somehow redirect from-source users to the new location. This is because ELPA users will be likely more common; mention of fetching the project from ELPA will be likely more common than mention of fetching the project from source. Forgetting this means users run a high risk of using a stale project for a long time.

Why both:

- The project will benefit from the potential quality increase that comes from going through an additional ELPA maintainer team's review(s).

- More access typically means more users; this typically results in better software, as mentioned before.

**Comment by manateelazycat** [comment]
https://manateelazycat.github.io/2018/10/07/why-not-melpa/
